{"name": "test_estimate_bridge_stablecoin_to_not_native[Polygon (MATIC)]", "status": "failed", "statusDetails": {"message": "AssertionError: Ожидался status = 200, пришел status = 400. Тело ответа: \n{\"ok\":false,\"data\":null,\"error\":\"call revert exception [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method=\\\"decimals()\\\", data=\\\"0x\\\", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.7.0)\"}.", "trace": "network = 'Polygon (MATIC)'\n\n    @pytest.mark.parametrize(\"network\", networks)\n    def test_estimate_bridge_stablecoin_to_not_native(network):\n        net = de_bridge_keys_data()[network].get('net')\n        stable_coin = de_bridge_keys_data()[network].get('stableCoin')\n        not_native_token = de_bridge_keys_data()[network].get('notNativeToken')\n>       DeBridge().EstimateBridge().estimate_bridge_stablecoin_to_not_native(net=net, stable_coin=stable_coin,\n                                                                             not_native_token=not_native_token)\n\ntests/api_tests/tests_de_bridge.py:31: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <serviceCalls.debrdige_service.DeBridge.EstimateBridge object at 0x10a945fa0>\nnet = 'polygon', stable_coin = '0x1af3f329e8be154074d8769d1ffa4ee058b1dbc3'\nnot_native_token = '0xa1428174f516f527fafdd146b883bb4428682737'\n\n    def estimate_bridge_stablecoin_to_not_native(self, net, stable_coin, not_native_token):\n        response = requests.get(\n            f\"{self.url}?srcNet={net}&srcTokenAddress={stable_coin}\"\n            f\"&srcTokenAmount=1&dstNet={net}&dstTokenAddress={not_native_token}\")\n        logger.info(f\"Отправлен запрос на роут - {response.url}\")\n        logger.info(response.text)\n>       assert response.status_code == 200, f\"Ожидался status = {200}, \" \\\n                                            f\"пришел status = {response.status_code}. \" \\\n                                            f\"Тело ответа: \\n{response.text}.\"\nE       AssertionError: Ожидался status = 200, пришел status = 400. Тело ответа: \nE       {\"ok\":false,\"data\":null,\"error\":\"call revert exception [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method=\\\"decimals()\\\", data=\\\"0x\\\", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.7.0)\"}.\n\nserviceCalls/debrdige_service.py:52: AssertionError"}, "attachments": [{"name": "log", "source": "e59f82c3-85d8-4e5b-a7aa-8d701db7aa9b-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "network", "value": "'Polygon (MATIC)'"}], "start": 1685619210342, "stop": 1685619210990, "uuid": "3c3d01ce-0ed2-4cf6-878e-91553293fa37", "historyId": "4b79ca5be9f6ba7ed6e1d4ef5fd39c0e", "testCaseId": "657d3a20abaf833d25983598fe444025", "fullName": "tests.api_tests.tests_de_bridge#test_estimate_bridge_stablecoin_to_not_native", "labels": [{"name": "parentSuite", "value": "tests.api_tests"}, {"name": "suite", "value": "tests_de_bridge"}, {"name": "host", "value": "MacBook-Air-Anna.local"}, {"name": "thread", "value": "18938-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.api_tests.tests_de_bridge"}]}