{
  "uid" : "cf2f0674fa22bf38",
  "name" : "test_estimate_bridge_stablecoin_to_not_native[Polygon (MATIC)]",
  "fullName" : "tests.api_tests.tests_de_bridge#test_estimate_bridge_stablecoin_to_not_native",
  "historyId" : "4b79ca5be9f6ba7ed6e1d4ef5fd39c0e",
  "time" : {
    "start" : 1686046585264,
    "stop" : 1686046585936,
    "duration" : 672
  },
  "status" : "failed",
  "statusMessage" : "AssertionError: Ожидался status = 200, пришел status = 400. Тело ответа: \n{\"ok\":false,\"data\":null,\"error\":\"call revert exception [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method=\\\"decimals()\\\", data=\\\"0x\\\", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.7.0)\"}.",
  "statusTrace" : "network = 'Polygon (MATIC)'\n\n    @pytest.mark.parametrize(\"network\", networks)\n    def test_estimate_bridge_stablecoin_to_not_native(network):\n        net = de_bridge_keys_data()[network].get('net')\n        stable_coin = de_bridge_keys_data()[network].get('stableCoin')\n        not_native_token = de_bridge_keys_data()[network].get('notNativeToken')\n>       DeBridge().EstimateBridge().estimate_bridge_stablecoin_to_not_native(net=net, stable_coin=stable_coin,\n                                                                             not_native_token=not_native_token)\n\ntests/api_tests/tests_de_bridge.py:31: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <serviceCalls.debrdige_service.DeBridge.EstimateBridge object at 0x7f151bd3ab20>\nnet = 'polygon', stable_coin = '0x1af3f329e8be154074d8769d1ffa4ee058b1dbc3'\nnot_native_token = '0xa1428174f516f527fafdd146b883bb4428682737'\n\n    def estimate_bridge_stablecoin_to_not_native(self, net, stable_coin, not_native_token):\n        response = requests.get(\n            f\"{self.url}?srcNet={net}&srcTokenAddress={stable_coin}\"\n            f\"&srcTokenAmount=10&dstNet={net}&dstTokenAddress={not_native_token}\")\n        logger.info(f\"Отправлен запрос на роут - {response.url}\")\n        logger.info(response.text)\n>       assert response.status_code == 200, f\"Ожидался status = {200}, \" \\\n                                            f\"пришел status = {response.status_code}. \" \\\n                                            f\"Тело ответа: \\n{response.text}.\"\nE       AssertionError: Ожидался status = 200, пришел status = 400. Тело ответа: \nE       {\"ok\":false,\"data\":null,\"error\":\"call revert exception [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method=\\\"decimals()\\\", data=\\\"0x\\\", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.7.0)\"}.\n\nserviceCalls/debrdige_service.py:52: AssertionError",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ ],
  "afterStages" : [ ],
  "labels" : [ {
    "name" : "parentSuite",
    "value" : "tests.api_tests"
  }, {
    "name" : "suite",
    "value" : "tests_de_bridge"
  }, {
    "name" : "host",
    "value" : "fv-az409-225"
  }, {
    "name" : "thread",
    "value" : "2536-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "tests.api_tests.tests_de_bridge"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ {
    "name" : "network",
    "value" : "'Polygon (MATIC)'"
  } ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "retries" : [ ],
    "categories" : [ {
      "name" : "Product defects",
      "matchedStatuses" : [ ],
      "flaky" : false
    } ],
    "tags" : [ ]
  },
  "source" : "cf2f0674fa22bf38.json",
  "parameterValues" : [ "'Polygon (MATIC)'" ]
}