{
  "uid" : "fb265bf131a53c0a",
  "name" : "test_estimate_bridge_not_native_to_not_native[Avalanche (AVAX)-Polygon (MATIC)]",
  "fullName" : "tests.api_tests.tests_de_bridge#test_estimate_bridge_not_native_to_not_native",
  "historyId" : "01b9b4e0725329110e5530e6aaa2555c",
  "time" : {
    "start" : 1686067377552,
    "stop" : 1686067378108,
    "duration" : 556
  },
  "status" : "failed",
  "statusMessage" : "AssertionError: Ожидался status = 200, пришел status = 400. Тело ответа: \n{\"ok\":false,\"data\":null,\"error\":\"missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (data=\\\"0x\\\", transaction={\\\"to\\\":\\\"0xa1428174F516F527fafdD146b883bB4428682737\\\",\\\"data\\\":\\\"0x313ce567\\\",\\\"accessList\\\":null}, error={\\\"reason\\\":\\\"processing response error\\\",\\\"code\\\":\\\"SERVER_ERROR\\\",\\\"body\\\":\\\"{\\\\\\\"jsonrpc\\\\\\\":\\\\\\\"2.0\\\\\\\",\\\\\\\"id\\\\\\\":\\\\\\\"44\\\\\\\",\\\\\\\"error\\\\\\\":{\\\\\\\"code\\\\\\\":90,\\\\\\\"message\\\\\\\":\\\\\\\"the evidence is sealed\\\\\\\"}}\\\",\\\"error\\\":{\\\"code\\\":90},\\\"requestBody\\\":\\\"{\\\\\\\"method\\\\\\\":\\\\\\\"eth_call\\\\\\\",\\\\\\\"params\\\\\\\":[{\\\\\\\"to\\\\\\\":\\\\\\\"0xa1428174f516f527fafdd146b883bb4428682737\\\\\\\",\\\\\\\"data\\\\\\\":\\\\\\\"0x313ce567\\\\\\\"},\\\\\\\"latest\\\\\\\"],\\\\\\\"id\\\\\\\":44,\\\\\\\"jsonrpc\\\\\\\":\\\\\\\"2.0\\\\\\\"}\\\",\\\"requestMethod\\\":\\\"POST\\\",\\\"url\\\":\\\"https://polygon-rpc.com\\\"}, code=CALL_EXCEPTION, version=providers/5.7.2)\"}.",
  "statusTrace" : "src_nets = 'Polygon (MATIC)', dst_nets = 'Avalanche (AVAX)'\n\n    @pytest.mark.parametrize(\"src_nets\", networks)\n    @pytest.mark.parametrize(\"dst_nets\", networks)\n    def test_estimate_bridge_not_native_to_not_native(src_nets, dst_nets):\n        src_net = de_bridge_keys_data()[src_nets].get('net')\n        dst_net = de_bridge_keys_data()[dst_nets].get('net')\n        src_not_native_token = de_bridge_keys_data()[src_nets].get('notNativeToken')\n        dst_not_native_token = de_bridge_keys_data()[dst_nets].get('notNativeToken')\n>       DeBridge().EstimateBridge().estimate_bridge_not_native_to_not_native(src_net=src_net, dst_net=dst_net,\n                                                                             src_not_native_token=src_not_native_token,\n                                                                             dst_not_native_token=dst_not_native_token)\n\ntests/api_tests/tests_de_bridge.py:60: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <serviceCalls.debrdige_service.DeBridge.EstimateBridge object at 0x7ffbb88f19a0>\nsrc_net = 'polygon', dst_net = 'avalanche'\nsrc_not_native_token = '0xa1428174f516f527fafdd146b883bb4428682737'\ndst_not_native_token = '0xe896cdeaac9615145c0ca09c8cd5c25bced6384c'\n\n    def estimate_bridge_not_native_to_not_native(self, src_net, dst_net, src_not_native_token,\n                                                 dst_not_native_token):\n        response = requests.get(\n            f\"{self.url}?srcNet={src_net}&srcTokenAddress={src_not_native_token}\"\n            f\"&srcTokenAmount=100000&dstNet={dst_net}&dstTokenAddress={dst_not_native_token}\")\n        logger.info(f\"Отправлен запрос на роут - {response.url}\")\n        logger.info(response.text)\n>       assert response.status_code == 200, f\"Ожидался status = {200}, \" \\\n                                            f\"пришел status = {response.status_code}. \" \\\n                                            f\"Тело ответа: \\n{response.text}.\"\nE       AssertionError: Ожидался status = 200, пришел status = 400. Тело ответа: \nE       {\"ok\":false,\"data\":null,\"error\":\"missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (data=\\\"0x\\\", transaction={\\\"to\\\":\\\"0xa1428174F516F527fafdD146b883bB4428682737\\\",\\\"data\\\":\\\"0x313ce567\\\",\\\"accessList\\\":null}, error={\\\"reason\\\":\\\"processing response error\\\",\\\"code\\\":\\\"SERVER_ERROR\\\",\\\"body\\\":\\\"{\\\\\\\"jsonrpc\\\\\\\":\\\\\\\"2.0\\\\\\\",\\\\\\\"id\\\\\\\":\\\\\\\"44\\\\\\\",\\\\\\\"error\\\\\\\":{\\\\\\\"code\\\\\\\":90,\\\\\\\"message\\\\\\\":\\\\\\\"the evidence is sealed\\\\\\\"}}\\\",\\\"error\\\":{\\\"code\\\":90},\\\"requestBody\\\":\\\"{\\\\\\\"method\\\\\\\":\\\\\\\"eth_call\\\\\\\",\\\\\\\"params\\\\\\\":[{\\\\\\\"to\\\\\\\":\\\\\\\"0xa1428174f516f527fafdd146b883bb4428682737\\\\\\\",\\\\\\\"data\\\\\\\":\\\\\\\"0x313ce567\\\\\\\"},\\\\\\\"latest\\\\\\\"],\\\\\\\"id\\\\\\\":44,\\\\\\\"jsonrpc\\\\\\\":\\\\\\\"2.0\\\\\\\"}\\\",\\\"requestMethod\\\":\\\"POST\\\",\\\"url\\\":\\\"https://polygon-rpc.com\\\"}, code=CALL_EXCEPTION, version=providers/5.7.2)\"}.\n\nserviceCalls/debrdige_service.py:81: AssertionError",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ ],
  "afterStages" : [ ],
  "labels" : [ {
    "name" : "parentSuite",
    "value" : "tests.api_tests"
  }, {
    "name" : "suite",
    "value" : "tests_de_bridge"
  }, {
    "name" : "host",
    "value" : "fv-az593-404"
  }, {
    "name" : "thread",
    "value" : "2504-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "tests.api_tests.tests_de_bridge"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ {
    "name" : "dst_nets",
    "value" : "'Avalanche (AVAX)'"
  }, {
    "name" : "src_nets",
    "value" : "'Polygon (MATIC)'"
  } ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "retries" : [ ],
    "categories" : [ {
      "name" : "Product defects",
      "matchedStatuses" : [ ],
      "flaky" : false
    } ],
    "tags" : [ ]
  },
  "source" : "fb265bf131a53c0a.json",
  "parameterValues" : [ "'Avalanche (AVAX)'", "'Polygon (MATIC)'" ]
}